### ISSUE TITLE
Firefox Stealing doesn't working on certains computer

### ISSUE THREAD

**Issue by FyR0z** [HackHound/PREC#2]
Hello, 

I have worked more than 2 hours on your Script for fix some shit !
All working good maybe FirefoxStealing doesn't working good !

So first i have modified this in your code:

![Image of my code](http://i.imgur.com/iuJt2rt.png)

Maybe I can't get FirefoxPassword on my PC and my VM (VitualBox)

List of compilation version i have tried:

> .NET 2
> .NET 4
> .NET4.5
> .NET 4.5.1

List of Windows version tested

> Windows 10 x64
> Windows 7 x64
> Windows 7 x32

Sorry for my english !
If you don't understand some things just contact me !

**Comment by Rottweiler** [comment]
Are you compiling to x86 architecture?

**Comment by FyR0z** [comment]
I have tested with x64 and x86 
Why ?

**Comment by Rottweiler** [comment]
I don't know what modifications you did to the code so I can't help you. It should be compiled to x86 that's all I can tell you.
