### ISSUE TITLE
Doesn't work am I doing it wrong ?

### ISSUE THREAD

**Issue by TheSph1nx** [HackHound/PREC#3]
Hello buddy, listen i can't find some good script to extract passwords but this one could be really good but i can't make this working. I've made what you said in the readme : i've added the 2 files into my project and in a normal form i called them like you wrote. But i don't get any message box or result in general.

I'm working on Visual Studio 2017 and i get no errors .. there's something more i have to do to get the results ? 

PS. Obviusly i got a lot of memorized passwords so the results are not empty.
Thanx

**Comment by Rottweiler** [comment]
Well this was made a long time ago and most browsers changed their encryption methods and storage methods
